language: python
python:
  - "3.7.6"
install:
  - cd schedulator_backend
  - pip install -r requirements.txt
  - cp .env.example .env
  - python manage.py makemigrations
  - python manage.py makemigrations crawler
  - python manage.py makemigrations api
  - python manage.py migrate
script:
  - python manage.py test
