# Generated by Django 2.2.6 on 2019-10-24 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crawler', '0003_section_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='section',
            name='type',
            field=models.CharField(choices=[('M', 'Master'), ('B', 'Bachelor')], default='B', max_length=1),
        ),
    ]
